const mongoose = require('mongoose');

const pushSubscriptionSchema = new mongoose.Schema({
    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    subscription: {
        type: Object, // Stores the endpoint and keys generated by the browser
        required: true
    }
});

module.exports = mongoose.model('PushSubscription', pushSubscriptionSchema);